export const LIST_CANDIDACY = 'LIST_CANDIDACY'
export const LIST_CANDIDACY_PENDING = `${LIST_CANDIDACY}_PENDING`
export const LIST_CANDIDACY_FULFILLED = `${LIST_CANDIDACY}_FULFILLED`
export const LIST_CANDIDACY_REJECTED = `${LIST_CANDIDACY}_REJECTED`

export const LIKE_CANDIDACY = 'LIKE_CANDIDACY'
export const LIKE_CANDIDACY_PENDING = `${LIKE_CANDIDACY}_PENDING`
export const LIKE_CANDIDACY_FULFILLED = `${LIKE_CANDIDACY}_FULFILLED`
export const LIKE_CANDIDACY_REJECTED = `${LIKE_CANDIDACY}_REJECTED`

export const POSTULATE_CANDIDACY = 'POSTULATE_CANDIDACY'
export const POSTULATE_CANDIDACY_PENDING = `${POSTULATE_CANDIDACY}_PENDING`
export const POSTULATE_CANDIDACY_FULFILLED = `${POSTULATE_CANDIDACY}_FULFILLED`
export const POSTULATE_CANDIDACY_REJECTED = `${POSTULATE_CANDIDACY}_REJECTED`
