export const LIST_CANDIDACY = 'LIST_CANDIDACY'
export const LIST_CANDIDACY_PENDING = `${LIST_CANDIDACY}_PENDING`
export const LIST_CANDIDACY_FULFILLED = `${LIST_CANDIDACY}_FULFILLED`
export const LIST_CANDIDACY_REJECTED = `${LIST_CANDIDACY}_REJECTED`
