export const LIST_EDUCATION = 'LIST_EDUCATION'
export const LIST_EDUCATION_PENDING = `${LIST_EDUCATION}_PENDING`
export const LIST_EDUCATION_FULFILLED = `${LIST_EDUCATION}_FULFILLED`
export const LIST_EDUCATION_REJECTED = `${LIST_EDUCATION}_REJECTED`
