export const LIST_EDUCATION = 'LIST_EDUCATION'
export const LIST_EDUCATION_PENDING = `${LIST_EDUCATION}_PENDING`
export const LIST_EDUCATION_FULFILLED = `${LIST_EDUCATION}_FULFILLED`
export const LIST_EDUCATION_REJECTED = `${LIST_EDUCATION}_REJECTED`

export const CREATE_EDUCATION = 'CREATE_EDUCATION'
export const CREATE_EDUCATION_PENDING = `${CREATE_EDUCATION}_PENDING`
export const CREATE_EDUCATION_FULFILLED = `${CREATE_EDUCATION}_FULFILLED`
export const CREATE_EDUCATION_REJECTED = `${CREATE_EDUCATION}_REJECTED`

export const UPDATE_EDUCATION = 'UPDATE_EDUCATION'
export const UPDATE_EDUCATION_PENDING = `${UPDATE_EDUCATION}_PENDING`
export const UPDATE_EDUCATION_FULFILLED = `${UPDATE_EDUCATION}_FULFILLED`
export const UPDATE_EDUCATION_REJECTED = `${UPDATE_EDUCATION}_REJECTED`

export const DESTROY_EDUCATION = 'DESTROY_EDUCATION'
export const DESTROY_EDUCATION_PENDING = `${DESTROY_EDUCATION}_PENDING`
export const DESTROY_EDUCATION_FULFILLED = `${DESTROY_EDUCATION}_FULFILLED`
export const DESTROY_EDUCATION_REJECTED = `${DESTROY_EDUCATION}_REJECTED`
