export const LIST_EXPERIENCE = 'LIST_EXPERIENCE'
export const LIST_EXPERIENCE_PENDING = `${LIST_EXPERIENCE}_PENDING`
export const LIST_EXPERIENCE_FULFILLED = `${LIST_EXPERIENCE}_FULFILLED`
export const LIST_EXPERIENCE_REJECTED = `${LIST_EXPERIENCE}_REJECTED`

export const CREATE_EXPERIENCE = 'CREATE_EXPERIENCE'
export const CREATE_EXPERIENCE_PENDING = `${CREATE_EXPERIENCE}_PENDING`
export const CREATE_EXPERIENCE_FULFILLED = `${CREATE_EXPERIENCE}_FULFILLED`
export const CREATE_EXPERIENCE_REJECTED = `${CREATE_EXPERIENCE}_REJECTED`

export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE'
export const UPDATE_EXPERIENCE_PENDING = `${UPDATE_EXPERIENCE}_PENDING`
export const UPDATE_EXPERIENCE_FULFILLED = `${UPDATE_EXPERIENCE}_FULFILLED`
export const UPDATE_EXPERIENCE_REJECTED = `${UPDATE_EXPERIENCE}_REJECTED`
