export const LIST_INTEREST = 'LIST_INTEREST'
export const LIST_INTEREST_PENDING = `${LIST_INTEREST}_PENDING`
export const LIST_INTEREST_FULFILLED = `${LIST_INTEREST}_FULFILLED`
export const LIST_INTEREST_REJECTED = `${LIST_INTEREST}_REJECTED`

export const DESTROY_INTEREST = 'DESTROY_INTEREST'
export const DESTROY_INTEREST_PENDING = `${DESTROY_INTEREST}_PENDING`
export const DESTROY_INTEREST_FULFILLED = `${DESTROY_INTEREST}_FULFILLED`
export const DESTROY_INTEREST_REJECTED = `${DESTROY_INTEREST}_REJECTED`

export const CREATE_INTEREST = 'CREATE_INTEREST'
export const CREATE_INTEREST_PENDING = `${CREATE_INTEREST}_PENDING`
export const CREATE_INTEREST_FULFILLED = `${CREATE_INTEREST}_FULFILLED`
export const CREATE_INTEREST_REJECTED = `${CREATE_INTEREST}_REJECTED`
