export const LIST_INTEREST = 'LIST_INTEREST'
export const LIST_INTEREST_PENDING = `${LIST_INTEREST}_PENDING`
export const LIST_INTEREST_FULFILLED = `${LIST_INTEREST}_FULFILLED`
export const LIST_INTEREST_REJECTED = `${LIST_INTEREST}_REJECTED`
