export const LIST_LANGUAGE = 'LIST_LANGUAGE'
export const LIST_LANGUAGE_PENDING = `${LIST_LANGUAGE}_PENDING`
export const LIST_LANGUAGE_FULFILLED = `${LIST_LANGUAGE}_FULFILLED`
export const LIST_LANGUAGE_REJECTED = `${LIST_LANGUAGE}_REJECTED`

export const CREATE_LANGUAGE = 'CREATE_LANGUAGE'
export const CREATE_LANGUAGE_PENDING = `${CREATE_LANGUAGE}_PENDING`
export const CREATE_LANGUAGE_FULFILLED = `${CREATE_LANGUAGE}_FULFILLED`
export const CREATE_LANGUAGE_REJECTED = `${CREATE_LANGUAGE}_REJECTED`

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
export const UPDATE_LANGUAGE_PENDING = `${UPDATE_LANGUAGE}_PENDING`
export const UPDATE_LANGUAGE_FULFILLED = `${UPDATE_LANGUAGE}_FULFILLED`
export const UPDATE_LANGUAGE_REJECTED = `${UPDATE_LANGUAGE}_REJECTED`

export const DESTROY_LANGUAGE = 'DESTROY_LANGUAGE'
export const DESTROY_LANGUAGE_PENDING = `${DESTROY_LANGUAGE}_PENDING`
export const DESTROY_LANGUAGE_FULFILLED = `${DESTROY_LANGUAGE}_FULFILLED`
export const DESTROY_LANGUAGE_REJECTED = `${DESTROY_LANGUAGE}_REJECTED`
