export const LIST_LANGUAGE = 'LIST_LANGUAGE'
export const LIST_LANGUAGE_PENDING = `${LIST_LANGUAGE}_PENDING`
export const LIST_LANGUAGE_FULFILLED = `${LIST_LANGUAGE}_FULFILLED`
export const LIST_LANGUAGE_REJECTED = `${LIST_LANGUAGE}_REJECTED`
