export const LIST_SKILL = 'LIST_SKILL'
export const LIST_SKILL_PENDING = `${LIST_SKILL}_PENDING`
export const LIST_SKILL_FULFILLED = `${LIST_SKILL}_FULFILLED`
export const LIST_SKILL_REJECTED = `${LIST_SKILL}_REJECTED`

export const DESTROY_SKILL = 'DESTROY_SKILL'
export const DESTROY_SKILL_PENDING = `${DESTROY_SKILL}_PENDING`
export const DESTROY_SKILL_FULFILLED = `${DESTROY_SKILL}_FULFILLED`
export const DESTROY_SKILL_REJECTED = `${DESTROY_SKILL}_REJECTED`
