export const LIST_SKILL = 'LIST_SKILL'
export const LIST_SKILL_PENDING = `${LIST_SKILL}_PENDING`
export const LIST_SKILL_FULFILLED = `${LIST_SKILL}_FULFILLED`
export const LIST_SKILL_REJECTED = `${LIST_SKILL}_REJECTED`
